.gitignore, README.rst, docs/source/api/index.rst, docs/source/api/util.rst, docs/source/installguide.rst, requirements.txt, setup.py, siphon/__init__.py, siphon/catalog.py, siphon/cdmr/cdmremote.py, siphon/cdmr/tests/dataset_tests.py, siphon/cdmr/tests/ncstream_tests.py, siphon/testing.py, siphon/tests/fixtures/top_thredds_catalog, siphon/tests/test_catalog.py, siphon/tests/test_util.py, siphon/util.py
=> Use requests for HTTP support.

docs/source/api/index.rst, docs/source/api/metadata.rst, docs/source/api/ncssdataset.rst, siphon/catalog.py, siphon/metadata.py, siphon/ncss_dataset.py, siphon/tests/fixtures/GFS_Global_0p5_Grid_Dataset_xml, siphon/tests/fixtures/Surface_Synoptic_Station_Dataset_xml, siphon/tests/fixtures/top_level_cat, siphon/tests/test_catalog.py, siphon/tests/test_metadata.py, siphon/tests/test_ncss_dataset.py
full implementation of gridded ncss dataset.xml doc
full implementation of point ncss dataset.xml doc
Testing for both
Sphinx docs
=> full implementation of ncss dataset.xml

siphon/catalog.py, siphon/metadata.py, siphon/ncss_dataset.py, siphon/tests/fixtures/radar_dataset_cat, siphon/tests/test_catalog.py
fixes #22
makes sure catalog variable elements are exposed in the same way as ncss_dataset variable elements dict of dicts.
=> Handle variables element in catalog

siphon/catalog.py, siphon/metadata.py, siphon/tests/fixtures/point_dataset_cat, siphon/tests/fixtures/point_feature_dataset_xml, siphon/tests/test_catalog.py
Fixes warning message reported in #28
More work to ensure attrs are actually required - see #30
=> Addresses #28

siphon/http_util.py, siphon/tests/test_http_util.py
=> changed lonlat_box() param order

.travis.yml, examples/requirements.txt, setup.py
Put example requirements as an extra in `setup.py`, and use this in .travis. Also fix a metpy reference.
=> More Travis

siphon/ncss_dataset.py, siphon/tests/test_metadata.py
fixes Unidata/siphon#71
fixes Unidata/siphon#72
=> Removed duplicate method and fixed metadata test

siphon/tests/fixtures/follow_cat, siphon/tests/test_catalog.py
Test was missing using VCR to replay request. Only noticed now that
thredds-test is down.
=> Fix test directly accessing thredds-test.

setup.py, siphon/cdmr/dataset.py, siphon/cdmr/ncStream_pb2.py, siphon/cdmr/ncstream.py, siphon/cdmr/tests/fixtures/nc4_chararray, siphon/cdmr/tests/fixtures/nc4_compound_ref_deflate, siphon/cdmr/tests/fixtures/nc4_nested_structure_scalar, siphon/cdmr/tests/fixtures/nc4_strings, siphon/cdmr/tests/fixtures/nc4_vlen, siphon/cdmr/tests/fixtures/tds5_basic, siphon/cdmr/tests/fixtures/tds5_compound_ref, siphon/cdmr/tests/fixtures/tds5_nested_structure_scalar, siphon/cdmr/tests/fixtures/tds5_opaque, siphon/cdmr/tests/fixtures/tds5_strings, siphon/cdmr/tests/fixtures/tds5_vlen, siphon/cdmr/tests/fixtures/tds5_vlen_slicing, siphon/cdmr/tests/test_dataset.py, siphon/cdmr/tests/test_ncstream.py, siphon/http_util.py
- Lots of changes to handle more fully the data model of CDMRemote v1 (TDS < 5)
- Vlen, Structs, etc.
- Implement support for new CDMRemote v2 (TDS >= 5)
- lots of tests
=> CDMRemote fixes

docs/source/api/catalog.rst, docs/source/api/http_util.rst, docs/source/api/metadata.rst, docs/source/api/ncss.rst, docs/source/api/ncssdataset.rst, docs/source/api/radarserver.rst, docs/source/conf.py, siphon/catalog.py, siphon/http_util.py, siphon/metadata.py, siphon/ncss.py, siphon/ncss_dataset.py, siphon/radarserver.py
- Add cross-linking to other projects in docs
- Clean up references to classes, etc.
- Fix mis-naming
- Re-arrange API docs
- clean up a bunch of pycharm, etc. warnings about static methods, etc.
=> Clean docs

siphon/catalog.py, siphon/metadata.py, siphon/ncss_dataset.py
=> Change default log level to ERROR

.travis.yml, docs/source/api/ncss.rst, docs/source/api/radarserver.rst
Things I'm finding as I prepare tutorial. Currently:
- Include inherited members for radarserver and ncss. This makes the docs for the query classes much better.
=> Documentation tweaks

appveyor.yml, examples/notebooks/NCSS_Example.ipynb
Data on thredds.ucar.edu moved around the pressure variable--finally do
this right and look at the `coordinates` attribute and figure out what
the right pressure variable is.
=> Fix NCSS example notebook.

.gitattributes, .travis.yml, docs/requirements.txt, docs/source/developerguide.rst, docs/source/index.rst, docs/source/installguide.rst, setup.cfg, setup.py
Clean-ups of setup.py and .travis.yml to keep things current and building. Also add git config for using nbdime for diffing notebooks.
=> Infrastructure fixes

siphon/metadata.py, siphon/ncss_dataset.py
There's no reason for the client to be so pedantic. Also change some
log.error to log.warning.
=> BUG: Make parsing more permissive.

README.rst, docs/source/_templates/footer.html, docs/source/conf.py, docs/source/developerguide.rst, docs/source/index.rst, docs/source/installguide.rst
Just cleans up some odds and ends after migrating.
=> Finish migration from RTD

siphon/http_util.py
Added information about using 'all' to ncss.query.variables to retrieve all
My playing shows this fetches all data.
=> DOCFIX: Added info about using 'all'

.github/CODEOWNERS, README.rst, SUPPORT.md
Adds a `SUPPORT` and `CODEOWNERS` file, as well as links to support from the `README`. Closes #141
=> GitHub enhancements

.travis.yml
Works around pypa/setuptools#1086 and pypa/setuptools#1101
=> MNT: Manually upgrade setuptools

.appveyor.yml
Turn example/doc builds back on. Closes #138
=> Examples and docs

docs/CONTRIBUTING.md, docs/citing.rst, docs/conf.py, docs/index.rst, setup.py
- Add a DOI and citation information
- Update some resources, including linking to the gallery
- Hide the table of contents from the landing page but leave it in the side bar
- Add the contributor's guide to the web documentation
=> Doc updates

examples/ncss/NCSS_Cartopy_Example.py
Looks like we only have one example using state borders, but this should be the last thing we maintain that needs these updates.
=> Modify state borders for Cartopy 0.16

siphon/tests/fixtures/acis_general, siphon/tests/fixtures/acis_griddata, siphon/tests/fixtures/acis_multistndata, siphon/tests/fixtures/acis_stndata, siphon/tests/test_acis.py
Fix by adding the missing decorator.
=> BUG: Not all ACIS tests were using VCR

.travis.yml, ci/deploy_docs.sh, ci/gen_versions_json.py
=> ENH: Add version chooser to docs

.travis.yml, docs/conf.py, environment.yml, setup.py
Accidentally broke exit code handling on Travis, fix that.
Will also fix failling metpy import.
=> Fix documentation build

.codecov.yml, siphon/catalog.py, siphon/tests/fixtures/ncei_cat_to_subset, siphon/tests/test_catalog_access.py, siphon/tests/test_metadata.py
Fixes #215. Adds support for NetcdfServer, when available, to be used for NCSS.
=> BUG: Fix NCEI NCSS access

siphon/catalog.py, siphon/tests/test_catalog_access.py
=> make filename parameter optional in catalog.download

environment.yml, examples/Basic_Usage.py, siphon/catalog.py, siphon/cdmr/tests/test_ncstream.py, siphon/http_util.py, siphon/simplewebservice/acis.py, siphon/tests/test_http_util.py, siphon/tests/test_ncss_dataset.py
- Improve message when server returns error (Fixes #222)
- Refactor session handling so that we can set default options, including authentication. (Fixes #117)
=> HTTP Client updates

setup.cfg, siphon/catalog.py, siphon/tests/test_catalog.py
=> Set dataset ID attribute

.travis.yml, AUTHORS.txt, CONTRIBUTING.md, examples/acis/Basic_Overview.py, examples/acis/Mapping_Example.py, examples/ncss/NCSS_Example.py, siphon/catalog.py, siphon/cdmr/ncstream.py, siphon/ncss.py, siphon/radarserver.py, siphon/simplewebservice/iastate.py, siphon/simplewebservice/igra2.py, siphon/simplewebservice/ndbc.py, siphon/simplewebservice/wyoming.py, siphon/tests/test_metadata.py, siphon/tests/test_ncss.py, siphon/tests/test_ncss_dataset.py, siphon/tests/test_ndbc.py
Travis had a lot of flake8 and a few assertion errors due to changes in how Pandas handles datetimes/Timestamps. I also updated the contributor's guide to be more in line with the MetPy version to encourage the usage of the Conda environment.
Note: I closed #268 and replaced with this identical PR due to a mistake I made with git in the previous branch.
=> MNT: flake8 and datetime fixes for Travis

siphon/simplewebservice/wyoming.py
Updates to wyoming.py to allow Precipitable Water measurements to be pulled.
=> precipitable water import

docs/_templates/footer.html
- Removing Inoperable "Say Thanks" Link
=> Removing Broken Link

docs/installguide.rst
Closes #305
-Fulfills request of mentioning install via conda-forge
-Adds another way for users to download Siphon onto their systems
=> New Feature: Adding conda-forge Prompt

ci/doc_requirements.txt
sphinx-gallery now lists this so no need for us to worry about it.
~- [ ] Tests added~
~- [ ] Fully documented~
=> Remove pillow dependency

.github/ISSUE_TEMPLATE/config.yml, .github/pull_request_template.md, .github/workflows/code-analysis.yml, .github/workflows/docs-conda.yml, .github/workflows/docs.yml, .github/workflows/linting.yml, .github/workflows/tests-conda.yml, .github/workflows/tests-pypi.yml, CONTRIBUTING.md, README.rst, docs/conf.py, docs/developerguide.rst, docs/index.rst
We have long since made this change elsewhere. Also take the opportunity to remove outdated badges for AppVeyor and Travis.
=> Change default branch to 'main'

examples/upperair/Wyoming_Request.py
Taken from Hurricane Helene timeframe. This gives much more useful data by default.
=> Update site/date/time for Wyoming Example

docs/conf.py
For some reason this started issuing a 403. We had already ignored StackOverflow for MetPy.
=> Skip stackoverflow link for linkchecker
