Unidata/siphon

siphon/catalog.py
siphon/metadata.py
siphon/tests/fixtures/top_level_20km_rap_catalog
siphon/tests/test_catalog.py
siphon/tests/test_metadata.py

Adds the ability to parse metadata blocks from TDS Client Catalogs, and only exposes services on a dataset that are defined by the ServiceName element contained in the metadata.

Added metadata parsing to TDSCatalog object

---

siphon/catalog.py
siphon/tests/fixtures/html_then_xml_catalog
siphon/tests/test_catalog.py

If TDSCatalog detects html, warn and try an XML link.

---

siphon/catalog.py
siphon/tests/test_catalog.py

The leading '/' in catalog references is needed to construct the full URL path from a catalog reference.
For instance, in the catalog `http://thredds-test.unidata.ucar.edu/thredds/testDatasets.xml` the reference `TestFmrc` points to `/thredds/catalog/fmrc/ecmwf/global_2p5/catalog.xml`. Resolving the relative URL should give `http://thredds-test.unidata.ucar.edu/thredds/catalog/fmrc/ecmwf/global_2p5/catalog.xml`. Removing the `/`, as is being done in `CatalogRef.__init__()`, means the URL is constructed relative to the current catalog path, rather than being relative to the hostname.

Preserve relative urls in catalog references

---

README.rst
docs/source/developerguide.rst
environment.yml

Adds an environment config (to make it easy to set up a devel environment), as well as updating the dev docs and the readme badges.

Add Conda information

---

siphon/ncss.py

These changes were made in response to the inability of python to open a temporary file twice on Windows systems, Permission Denied error, thus preventing ncss.get_data() queries in Siphon. [Issue #24 NetCDF tempfile handling broken on windows](https://github.com/Unidata/siphon/issues/24).
The temporary file is now persistent but is then deleted at exit. The temporary file will only be removed if .close() method is called on the netCDF Dataset. With this fix the error message disappears and all nosetests pass. It has not been tested on Linux/Unix.
Siphon v0.3.1
Code that reproduces the error (also fails 2 nosetests; test_netcdf_point, test_netcdf4_point):
best_gfs = TDSCatalog('http://thredds.ucar.edu/thredds/catalog/grib/NCEP/GFS/Global_0p5deg/catalog.xml?dataset=grib/NCEP/GFS/Global_0p5d …

Fix: ncss netcdf temp file permission error on Windows

---

siphon/catalog.py
siphon/tests/fixtures/radarserver_ds_denied
siphon/tests/fixtures/radarserver_toplevel_denied
siphon/tests/test_radarsever.py

Make `requests` raise for http errors so that we get notified of problems right away. This fixes non-edu folks hitting the AWS TDS and getting strange Siphon errors rather than a clear message about not being allowed.

Http errors

---

.travis.yml
requirements.txt
setup.py

Rework travis config:
- Build wheels for new versions as needed and get/store in S3.
- Refactor build matrix to be a bit cleaner
- Only install pandoc for doc build
- Use the 'test' extra defined in setup.py to get dependencies.
- Add builds against Travis' nightly and 3.5-dev Python development builds, with pre-release packages

Travis updates

---

docs/requirements.txt
docs/source/notebook_gen_sphinxext.py
setup.py

This improves documentation builds. Removing netCDF4 as a **requirement** should smooth the way to building on RTFD which is currently broken; we were conditionally importing it anyways, and only for NCSS support.
Moving to nbconvert gets closer to actually specifying what we need for our docs; unfortunately, it still (4.0) has an undocumented dependency on `IPython.core`. This should be resolved in 4.1 (see jupyter/nbconvert#122)

Package updates

---

.coveragerc
.gitignore
.travis.yml
CONTRIBUTING.md
README.rst
docs/source/developerguide.rst
environment.yml
pytest.ini
setup.cfg
setup.py
siphon/cdmr/tests/test_dataset.py
siphon/cdmr/tests/test_ncstream.py
siphon/tests/test_catalog.py
siphon/tests/test_http_util.py
siphon/tests/test_metadata.py
siphon/tests/test_ncss.py
siphon/tests/test_ncss_dataset.py
siphon/tests/test_radarsever.py

Fixes #81.
Nose is unmaintained and the community at large seems to be adopting py.test.
Nothing serious to convert, other than no longer using nose's helpers. py.test does sensible things with regular `assert` so this is fine.

Replace nosetests with py.test

---

environment.yml
siphon/catalog.py
siphon/tests/test_catalog.py

This uses OrderedDict to store datasets and catalog refs. This gives those items in the order they appear in the catalog, which is more sensible.

Use OrderedDict for TDSCatalog

---

siphon/catalog.py
siphon/metadata.py

In TDS 4.6, the latest service had a `name` of `Latest` and a `serviceType` of `Resolver`, at least on Unidata servers. In 5.0, the name has changed to simply `Resolver`, as part of the new Standard Service feature. The name was always configurable by the server admin, so there is no need to explicitly check the `service` elements `name` attribute.
Also in this PR is change to make invalid values for THREDDS Catalog Metadata less noisy, as they are not all that importiant for the end users to see. This second commit sets the log level to ERROR instead of WARNING.

Latest dataset issue

---

siphon/catalog.py
siphon/tests/fixtures/cat_access_elements
siphon/tests/test_catalog.py

Fix Unidata/siphon#114
Fix Unidata/siphon#115

Process dataset elements with access children

---

siphon/metadata.py
siphon/tests/fixtures/cat_non_standard_context_path
siphon/tests/test_metadata.py

We get a validation warning in our test suite due to an attribute added to a catalog that is not under our control.

Fix validation warning in tests

---

docs/conf.py
siphon/catalog.py
siphon/ncss.py
siphon/ncss_dataset.py
siphon/tests/test_ncss_dataset.py

Before these changes, we only handled types `int` and `float` when parsing dataset.xml - everything else was left as a string and logged a warning. Even with this PR, we still do not handle:
* Sequence
* Structure
* enum
* opaque
* object
* char
because I do not have an example of those, and honestly have no idea what to do with some.

Handle more data types when parsing dataset.xml

---

siphon/ncss.py
siphon/tests/test_ncss.py

Manually cast set of variables to bool when returning.

BUG: Fix empty set returned from validate_query (Fixes #102)

---

.appveyor.yml
.prospector.yaml
.travis.yml
examples/Basic_Usage.py
examples/Radar_Server_Level_3.py
examples/ncss/NCSS_Cartopy_Example.py
examples/ncss/NCSS_Example.py
examples/ncss/NCSS_Timeseries_Examples.py
siphon/catalog.py
siphon/tests/fixtures/cat_to_cdmr
siphon/tests/fixtures/cat_to_open
siphon/tests/fixtures/cat_to_opendap
siphon/tests/fixtures/cat_to_subset
siphon/tests/test_catalog.py
siphon/tests/test_catalog_access.py

A lot of changes to smooth over the API:
- Add index-based access to collections of datasets and catalog refs (#134)
- Add date time-based filtering of those collections (#135)
- Add methods to simplify remote access (#136)
- Add a `latest` attribute to simplify access to latest dataset (#137)
This leaves adding the `format` option to `subset` to future work. I also punted on best/collection since those aren't easily programmatically determined.

Improve API

---

setup.py

Without this one get a bad string version:
```python
import siphon
print(siphon.__version__)
0+unknown
```

fix version string

---

siphon/tests/test_catalog_access.py

We can't catch the HTTP request for opendap access, so this test
requires hitting the server (and the data has aged off). We don't want
tests hitting live data, so just nuke the test (might cause a line or
two to be untested, but alas...)
This should fix the build.

BUG: Don't try to test opendap access

---

.appveyor.yml
.coveragerc
siphon/catalog.py
siphon/tests/fixtures/cat_only_http
siphon/tests/test_catalog.py

Catalogs are allowed to specify the name of a service that is contained
within a compound service. Siphon was not properly creating the access
urls dictionary for this case.

BUG: Fix access_urls for some services

---

docs/api/index.rst
docs/api/simplewebservice.rst
examples/upperair/README.txt
examples/upperair/Wyoming_Request.py
setup.py
siphon/simplewebservice/__init__.py

* Add example of upper air request from Wyoming.
* Add to API docs.
Closes #155

Upper air data exposure

---

siphon/tests/test_http_util.py

It now warns about variables named 'l', since they are easily confused
with '1'. Changing all of these did seem to result in better code
regardless.

MNT: Fix style lint from flake8 3.5

---

siphon/catalog.py
siphon/cdmr/tests/test_coveragedataset.py
siphon/radarserver.py
siphon/simplewebservice/wyoming.py
siphon/tests/fixtures/rsmas_ramadda
siphon/tests/fixtures/rsmas_ramadda_datasets
siphon/tests/fixtures/tds50_catalogref_follow
siphon/tests/test_catalog.py

- Handle RAMADDA TDS catalogs by allowing for no name attribute on catalog refs (just use title)
- Fix generating access URLs for RAMADDA (which uses a full URL for services) by properly using `urljoin`
- Fix catalog reference URL generation on TDS 5 by making sure we use the url from the response as the actual catalog URL (handles forwards)

Various catalog fixes

---

siphon/catalog.py

Can reevaluate if necessary, but client catalog spec is case sensitive.

Don't be so lenient in check for Resolver service

---

environment.yml
siphon/catalog.py
siphon/tests/test_catalog.py

Should make working with siphon easier for folks. closes #158

Add string representations for catalogref and dataset

---

siphon/__init__.py
siphon/ncss_dataset.py
siphon/tests/fixtures/GFS_TDS5
siphon/tests/test_ncss_dataset.py

This fixes some errors and a bunch of warnings in parsing the `dataset.xml` on a TDS 5.0 grib collection.

TDS5 NCSS fixes

---

examples/upperair/Wyoming_Request.py
siphon/simplewebservice/wyoming.py

flake8-import-order 0.15 stopped silencing some messages, so now we see
a few inconsistencies in our formatting. Fix them.

MNT: Fix some import lint

---

siphon/cdmr/xarray_support.py

It looks like xarray 0.10 changed up how the backends operate, breaking
our CDM support in the process. This seems to get things back to
working.

MNT: Fix xarray support with xarray 0.10

---

siphon/catalog.py
siphon/tests/test_catalog.py

Fixes issue #172 so that filter_time_nearest searches for days 30 and 31 work properly.

Change line 44 to include 0123 for day instead of 012

---

siphon/http_util.py
siphon/tests/fixtures/gfs-error-no-header
siphon/tests/test_http_util.py

We were assuming that Content-Type was always available in the headers, which isn't the case when NCSS fails.
This changes:
```pytb
Traceback (most recent call last):
File "250hPa_Hemispheric_Plot.py", line 46, in <module>
data = ncss.get_data(gfsdata)
File "/Users/rmay/repos/siphon/siphon/ncss.py", line 114, in get_data
resp = self.get_query(query)
File "/Users/rmay/repos/siphon/siphon/http_util.py", line 379, in get_query
return self.get(url, query)
File "/Users/rmay/repos/siphon/siphon/http_util.py", line 457, in get
if resp.headers['Content-Type'].startswith('text/html'):
File "/Users/rmay/miniconda3/envs/py36/lib/python3.6/site-packages/requests/structures.py", line 54, in __getitem__
return self._store[key.lower()][1]
KeyError: 'content-type'
```
to
```pytb
Traceback (most recent …
```

BUG: Fix error path in HTTPEndPoint

---

siphon/metadata.py
siphon/tests/fixtures/ncei_embedded_metadata
siphon/tests/test_catalog.py
siphon/tests/test_metadata.py

Addresses the case where a metadata element pointing to an external metadata document, via xlink, is a child of a parent metadata element.
Fixes Unidata/siphon#179

BUG: Fix embedded metadata elements

---

environment.yml
setup.py
siphon/cdmr/xarray_support.py

XArray reworked some of the classes that support our CDMRemote backend, so we need to update. This also means that this (admittedly under exposed) code only works with xarray >=0.10.2, so bump the requirements for it.

MNT: Fix with xarray 0.10.2 (Fixes #192)

---

siphon/simplewebservice/iastate.py
siphon/tests/fixtures/iastate_high_alt_sounding
siphon/tests/fixtures/iastate_sounding
siphon/tests/test_iastate.py
siphon/tests/test_wyoming.py

Closes #156 by porting the IA State upper air data functionality over from MetPy. Also fixes a typo in Wyoming and lack of test coverage there. I'll work on #189 for both Wyoming and Iowa after this.

Port Iowa State Soundings from MetPy

---

examples/ncss/NCSS_Example.py
examples/ncss/NCSS_Timeseries_Examples.py
siphon/catalog.py
siphon/ncss.py
siphon/ncss_dataset.py
siphon/radarserver.py

For most cases it's completely unnecessary and longer. Just iterate over the dict directly.

MNT: Remove calls to dict.keys()

---

examples/upperair/IGRA2_Request.py
examples/upperair/README.txt
siphon/simplewebservice/igra2.py
siphon/tests/test_igra2.py

I modeled the IGRA2 capability on the Wyoming Upper Air code, so to the user the functionality should appear the same. Inside it's a little more complicated, as the IGRA2 data exists as zipped text files, with each text file including the full station sounding record (in some cases going back to the 1930s). Most of the code is simply encoding the formatting from the IGRA2 read me files - it's not as simple as the Wyoming requests since the sounding headers do not include column names, but rather include metadata and calculated variables. The function allows the user to request a single sounding or all the soundings within a time span. 
The file IGRA2_Request.py shows examples for single soundings from the standard and derived archives, and for pulling data ranges.

Adding function to read in IGRA2 upper air data

---

siphon/catalog.py
siphon/cdmr/coveragedataset.py
siphon/cdmr/dataset.py
siphon/cdmr/ncstream.py
siphon/metadata.py
siphon/ncss_dataset.py
siphon/tests/test_catalog.py

Instead of manually adding a stream handler, use `basicConfig()`, which sets up a default formatter and stream handler. It also allows us to set a default logging level, which makes it easier for users to override. It's not entirely the same as before, as we were setting different level for different modules. But at least in this case, user settings for logging will take precedence, regardless of whether they set it before or after they import siphon modules.

MNT: Improve logging set up

---

siphon/simplewebservice/iastate.py
siphon/simplewebservice/wyoming.py
siphon/tests/test_iastate.py
siphon/tests/test_wyoming.py

Closes #189 by adding time and other meta data to the returned soundings from Iowa and Wyoming.

Sounding metadata

---

examples/acis/Basic_Overview.py
siphon/simplewebservice/wyoming.py

Closes #176 and improves the region functionality. Users can specify human readable names instead of the abbreviations (which aren't listed anywhere I've found). The region will also be case insensitive. Adds a test for making sure the region is valid or a helpful `KeyError` is raised.

UW sounding regions

---

siphon/catalog.py
siphon/tests/fixtures/latest_resolver_on_latest_dataset
siphon/tests/test_catalog.py

Fixes issue Unidata/siphon#170

BUG: Fix check for latest on CompoundService

---

examples/upperair/Wyoming_Request.py

Add attaching units to upper air example

---

docs/_static/theme_override.css
docs/_templates/breadcrumbs.html
docs/conf.py
docs/index.rst

Pull in stuff from metpy and make it match metpy better:
- "Improve this page" link (thanks @leouieda)
- Add siphon logo to upper left corner
We need to figure out how to standardize this config, templates, etc.

Cleanup doc config

---

siphon/simplewebservice/igra2.py

I learned that Pandas uses functions in the `converters` dictionary prior to applying the `na_values`, so I added a check for na_values inside my converter function.

corrected bug where na_values were bypassed

---

.travis.yml
README.rst
SUPPORT.md
docs/index.rst
docs/installguide.rst

- Add information about dropping Python 2.7
- Update support links
- Add information about semantic versioning

Doc updates

---

siphon/simplewebservice/igra2.py

There was an order of operations issue where the data being read `dewpoint_depression` was being subtracted from `temperature` before the field was flagged for missing values.  This pull request simply changes the field being flagged and does the flagging before `dewpoint` is calculated, resulting in properly flagged `dewpoints`.

Fix for IGRA dewpoint calculation

---

siphon/catalog.py
siphon/tests/fixtures/thredds-test-default-5-0
siphon/tests/test_catalog.py
siphon/tests/test_catalog_access.py

Use case-insensitive comparisons for service names to handle catalog xmls which define either "OPenDAP", "OPENDAP", or "opendap", for example.

add case-insensitive strings and dicts for service types

---

siphon/simplewebservice/wyoming.py
siphon/tests/fixtures/wyoming_sounding_no_station
siphon/tests/test_wyoming.py

Closes #238 
Deals with missing lines from the wyoming archive when the station has a number, but no identifier.

Add capability to deal with stations with no identifier from Wyoming

---

siphon/catalog.py
siphon/tests/test_catalog_access.py

ENH: Add the option to return xarray from catalog helpers (Fixes #229)

---

docs/installguide.rst

Added `conda install -c unidata siphon` to install docs

DOC: Add conda instructions to installation guide

---

.appveyor.yml
CONTRIBUTING.md
docs/developerguide.rst
docs/index.rst
docs/installguide.rst
siphon/simplewebservice/ndbc.py

Need to use raw strings now for strings with things like `\s`, even though it isn't a valid escape code.

MNT: Fix bad escape codes

---

.travis.yml
environment.yml
setup.cfg
setup.py
siphon/cdmr/tests/test_dataset.py
siphon/simplewebservice/igra2.py

A variety of little things:
* Add `python_requires` to `setup.py`, which will be good as the next release is the last for 2.7
* Update Travis config to no longer build Python 3.6-dev, but instead add doc build on 3.7-dev
* Enable a couple more flake8 plugins
This should fail initially with the new plugins, at which point I'll add a commit fixing the failures.

More Maintenance

---

docs/conf.py
examples/ndbc/buoy_met_request.py
siphon/catalog.py
siphon/http_util.py
siphon/tests/test_catalog.py
siphon/tests/test_http_util.py

Adds warning to time range methods in `Catalog` and `http_util` if the time range is invalid.

Add warning if time range is invalid

---

siphon/cdmr/xarray_support.py

Update importing FrozenDict call for xarray v0.14

Update xarray FrozenDict call 

---

siphon/simplewebservice/iastate.py
siphon/tests/fixtures/iastate_sounding_with_nans
siphon/tests/test_iastate.py

Adds a flag to interpolate NaNs for temperature and dewpoint at significant wind levels. Default is False, so the default return does not change. To do this interpolation, it makes use of pandas `interpolate()`, which is linear. This saves the end user from figuring out how to do this with pandas themselves and allows for similar code to the Wyoming returns by just adding `interp_nans=True` to the `.request_data()` call.

Add flag for IAState to interpolate NaNs 

---

siphon/simplewebservice/igra2.py

All the was missing was the column name, column units, and column conversion function for the column "relative_humidity_gradient" in the igra2-derived import function.

fixed rhgrad import issue

---

siphon/catalog.py
siphon/tests/fixtures/fronts_cat_open
siphon/tests/test_catalog_access.py

This allows getting back the results of remote_open() using a StringIO object, rather than BytesIO. This is useful e.g. to pass to MetPy's parsing functions. The call works as:
```python
cat = TDSCatalog(url)
fobj = cat.datasets[0].remote_open(mode='t', errors='replace')
```

Add mode option for remote_open()

---

.github/workflows/docs-conda.yml
README.rst
docs/index.rst
docs/installguide.rst
examples/Basic_Usage.py
examples/ncss/NCSS_Cartopy_Example.py
examples/ncss/NCSS_Example.py
examples/ncss/NCSS_Timeseries_Examples.py
setup.py
src/siphon/catalog.py
src/siphon/cdmr/cdmremote.py
src/siphon/cdmr/coveragedataset.py
src/siphon/cdmr/dataset.py
src/siphon/cdmr/ncstream.py
src/siphon/http_util.py
src/siphon/metadata.py
src/siphon/ncss.py
src/siphon/ncss_dataset.py
src/siphon/radarserver.py
src/siphon/simplewebservice/iastate.py
src/siphon/simplewebservice/igra2.py
src/siphon/simplewebservice/ndbc.py
src/siphon/simplewebservice/wyoming.py
tests/test_http_util.py
tests/test_metadata.py
tests/test_ncss.py
tests/test_ncss_dataset.py
tests/test_radarsever.py

* Finally drop 2.7 (#214)
* Drop Python 3.6
* Update CI a bit
~- [ ] Tests added~

Update Python versions

---

setup.cfg
setup.py

Copy mostly-verbatim `setup.py` content into `setup.cfg`.
- ~~Tests added~~
- ~~Fully documented~~

MNT: move setup.py content into setup.cfg

---

src/siphon/catalog.py
src/siphon/cdmr/coveragedataset.py
src/siphon/cdmr/dataset.py
src/siphon/cdmr/ncstream.py
src/siphon/metadata.py
src/siphon/ncss_dataset.py

This PR sets the logging level using the module-level loggers instead of using `logging.basicConfig(level=)`.
Running `grep -Rn logging.basicConfig --include=*.py` in the root directory of the repo should return nothing now. To check that this solved the issue, try running the following code without the changes, and then with the changes:
```python
import logging
from siphon.catalog import TDSCatalog
logger = logging.getLogger(__name__)
logger.setLevel("INFO")
stream_handler = logging.StreamHandler()
formatter = logging.Formatter(
fmt="%(asctime)s - $(levelname)s - %(message)s",
datefmt="%Y-%m-%d %H:%M:%S",
)
stream_handler.setFormatter(formatter)
logger.addHandler(stream_handler)
logger.debug("This is a debug test")
logger.info("This is an info test")
logger.warning("This is a warning …
```

Set log level in each module instead of using logging.basicConfig

---

src/siphon/catalog.py
tests/fixtures/nasa_hyrax_dataset
tests/test_catalog.py

Due to the way parsing is done, we look backwards (on when a dataset tag is encountered) to handle datasets with embedded access tags. Unfortunately, this left us not handling the last such dataset encountered if it contained such tags, like is done on NASA's Hyrax server.
Ping @lesserwhirls (or @haileyajohnson) in case you see a better way to handle this. Really, I'm not at all happy how we're parsing right now (stateful, flat iteration) and would really love to restructure it. Unfortunately, I don't understand all the nuanced cases, nor are those cycles available. It just seems like it would be a LOT better if we could make use of the hierarchy present in the XML.

Fix dataset parsing for Hyrax catalogs

---

ci/requirements.txt

* Bumps ci version to 5.28.2 (since 5.28.3 isn't available on conda-forge yet)

Bump protobuf to 5.28.2

---

.github/workflows/nightly-builds.yml
.github/workflows/run-unstable-pr.yml
.github/workflows/unstable-builds.yml

This copies over the workflows from MetPy. It adds a job to run with unstable dependencies on a "nightly"/cronjob basis, as well as a job for a PR to run these as needed.

Add workflows for unstable dependencies

---

.github/workflows/docs-conda.yml
.github/workflows/docs.yml
.github/workflows/tests-conda.yml
.github/workflows/tests-pypi.yml
pyproject.toml

Add Python 3.13 to our CI build matrices and add it to our package metadata as supported.

Python 3.13

---

.github/dependabot.yml
.github/workflows/automerge-dependabot.yml
.github/workflows/nightly-builds.yml

* Reduce Dependabot frequency to weekly since we're up to date; this should help with spurious failures, especially when waiting for conda-forge to upload matching packages
* Sync better labling/messages from MetPy for Dependabot PRs
* Add workflow (from MetPy) to auto-merge Dependabot PRs
* Shift "nightly" builds to 9:30Z to try to avoid issues with data not being available at the top of the hour(seen in #838)

Update dependabot & nightly workflows

---

src/siphon/ncss_dataset.py
tests/fixtures/RAP_TDS5
tests/test_catalog.py
tests/test_ncss_dataset.py

Cleanup NCSS warnings

---

src/siphon/catalog.py

Closes #361 with a documentation-update.

Expand documentation on indexing and interation for DatasetCollection

---

src/siphon/simplewebservice/igra2.py
tests/test_igra2.py

We're already scanning the whole archive, just note the max/min date encountered.

Improve igra2 date error message

---

src/siphon/simplewebservice/wyoming.py
tests/fixtures/wyoming_sounding_recalculate
tests/test_wyoming.py

Allows for data from the Wyoming soundings site to be recalculated which overwrites a possibly incomplete cache on their site. I believe this is the issue pointed out in #310, but I am not entirely sure.
I am new to this process, so please forgive any mistakes I have made. This especially extends to the test that I included.

Recalculate Wyoming

---

src/siphon/catalog.py
tests/fixtures/oceandata_hyrax_dataset
tests/test_catalog.py

* Fix generation of access urls for the oceandata hyrax catalog caused by improper use of `urljoin()`. This breaks handling of urlpath in the Ramadda catalog "opendap link", but at this point I consider that a Ramadda bug, not something actually allowed by the [TDS Client Catalog Spec](https://docs.unidata.ucar.edu/tds/current/userguide/client_side_catalog_specification.html#constructing-urls), which explicitly states that the service base and the urlpath should be directly concatenated
* This revealed a bug where the 'dap' link in the hyrax catalog would not be used for `remote_access()`. It turned out we were improperly mapping this url to the service type, and using the service name instead
* Also go ahead and support DODS as an alias for OPENDAP, and http as an alias for HTTPServer in …

Fix oceandata hyrax catalog issues

---

.github/workflows/tests-pypi.yml
ci/requirements.txt

Urllib3 2.3.0 is not compatible with the current (6.0.2) version of vcrpy (see kevin1024/vcrpy#888).

CI: Pin urllib3 to v2.2.3

---

LICENSE

Only bumping to 2024 since nothing copyrightable has been done in 2025 to date.

Bump copyright year in license
